import Providers from './components/Providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: 'Arial, Helvetica, sans-serif' }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
